name: Sync To CNB

on:
  push:
    branches:
      - rewrite

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push To CNB
        run: |
          git remote add cnb https://${{ secrets.CNB_USERNAME }}:${{ secrets.CNB_TOKEN }}@cnb.cool/ETS2LA-CN/Euro-Truck-Simulator-2-Lane-Assist.git

          echo "=== TEST CONNECTION ==="
          git ls-remote cnb

          echo "=== CURRENT BRANCH ==="
          git branch

          echo "=== PUSH ==="
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push cnb rewrite --verbose
